language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
env:
  global:
    - PORT=3000
script:
  - yarn lint
  - yarn test
  - yarn build
after_success: yarn coverage
